spring:
  h2:
    console:
      enabled: false
  devtools:
    livereload:
      enabled: false
  jpa:
    open-in-view: true
    properties:
      hibernate:
        #dialect: edu.nju.se.teamnamecannotbeempty.data.MyDialect
        show_sql: false
        format_sql: false
        order_inserts: true
        order_updates: true
        jdbc:
          batch_versioned_data: true
          batch_size: 500
    hibernate:
      ddl-auto: none
    database-platform: edu.nju.se.teamnamecannotbeempty.data.MyDialect
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/segjjs?serverTimezone=CTT&characterEncoding=UTF-8
    username: root
    password: root
server:
  port: 9910
rmi:
  host: localhost


#spring:
#  devtools:
#    livereload:
#      enabled: false
#  jpa:
#    hibernate:
#      ddl-auto: none
#    open-in-view: true
#    properties:
#      hibernate:
#        order_inserts: true
#        order_updates: true
#        jdbc:
#          batch_versioned_data: true
#          batch_size: 500
#server:
#  port: 9910
#rmi:
#  host: localhost